kafka:
  bootstrap_servers: localhost:9092
  group_id: group
  scan_startup_mode: earliest-offset

flink:
  flink_home: /opt/flink
  environment_settings:
    streaming_mode: true
    use_blink_planner: true
  pipeline_jars: file:///Users/lethanhtan/PycharmProjects/flink_kafka_to_kafka/packages/lib/flink-connector-kafka_2.12-1.14.6.jar;file:///Users/lethanhtan/PycharmProjects/flink_kafka_to_kafka/packages/lib/kafka-clients-2.4.1.jar