kafka:
  bootstrap_servers: localhost:9092
  group_id: group
  scan_startup_mode: earliest-offset

flink:
  flink_home: /opt/flink
  environment_settings:
    streaming_mode: true
    use_blink_planner: true
  pipeline:
    jars:
    - file:////Users/tanle/Documents/ThanhTanLe/PycharmProjects/learn_apache_flink_from_scratch/packages/lib/flink-connector-kafka_1.16.3.jar
    - file:////Users/tanle/Documents/ThanhTanLe/PycharmProjects/learn_apache_flink_from_scratch/packages/lib/kafka-clients-2.4.1.jar
    - file:////Users/tanle/Documents/ThanhTanLe/PycharmProjects/learn_apache_flink_from_scratch/packages/lib/postgresql-42.6.2.jar
    - file:////Users/tanle/Documents/ThanhTanLe/PycharmProjects/learn_apache_flink_from_scratch/packages/lib/flink-connector-jdbc_1.16.3.jar

  checkpoint:
    type: filesystem
    storage: file:///Users/tanle/Documents/ThanhTanLe/PycharmProjects/learn_apache_flink_from_scratch/packages/flink-state-backend/checkpoints/
    interval: 5000
    timeout: 60000
    max_concurrent: 1

database:
  host: localhost
  port: 5432
  database: finance_db
  username: admin
  password: 123456
  url: jdbc:postgresql://localhost:5432/finance_db